apiVersion: v1
data:
  access-key: bG9jYWwtYWNjZXNz #gitleaks:allow
  secret-key: bG9jYWwtc2VjcmV0 #gitleaks:allow
  bucket: Z2VvcGFycXVldA== #gitleaks:allow
kind: Secret
metadata:
  name: artifacts-minio
  namespace: gis-team